# Generated by Django 6.0.3 on 2026-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Me', max_length=100)),
                ('bio', models.TextField(default="I'm an IT student and graphic designer passionate about visual storytelling.")),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='frankneiltaag@email.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/')),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='EducationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Negros Oriental State University Bayawan-Sta. Catalina Campus', max_length=200)),
                ('student_name', models.CharField(default='Frank Neil Taganili', max_length=100)),
                ('course', models.CharField(default='Bachelor of Science in Information Technology', max_length=200)),
                ('year_level', models.CharField(default='3rd Year', max_length=50)),
                ('description', models.TextField(default='An IT student with a strong passion for graphic design and digital arts, combining technical skills with creativity to produce visually engaging designs.')),
            ],
            options={
                'verbose_name': 'Education Section',
                'verbose_name_plural': 'Education Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Frank Neil Taganili', max_length=100)),
                ('title', models.CharField(default='Graphic Designer', max_length=100)),
                ('tagline', models.CharField(default='Crafting visuals that speak louder than words.', max_length=255)),
                ('cta_button_text', models.CharField(default='View My Work', max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class, e.g. fa-brands fa-adobe', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order'],
            },
        ),
    ]
