# Generated by Django 6.0.3 on 2026-03-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='profile_image',
        ),
    ]
